typography_spectrum: 0.1999909246806055
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.2036941996775568
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.316433169413358
  brandStrength: 0.3222089179325849
  rhythmicContrast: 0.1654756371863186
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  lightness: 0.7002324936911464
purpose: []
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: The Orbital Experience
