name: The Orbital Experience
favicon: null
layout_spectrum: 0.20369419967755675
typography_spectrum: 0.19999092468060553
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3222089179325849
  lightness: 0.7002324936911464
  saturation: 0.316433169413358
  rhythmicContrast: 0.16547563718631864
purpose: []
